# Generated by Django 3.1.2 on 2020-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
    ]
