# Generated by Django 3.1.2 on 2020-11-01 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_business_neighborhood_occupant'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupant',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
