# Generated by Django 3.1.2 on 2020-11-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_auto_20201101_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='occupants_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
