# Generated by Django 3.1.2 on 2020-11-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_auto_20201101_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.neighborhood'),
        ),
    ]
