# Generated by Django 3.1.2 on 2020-11-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0010_auto_20201101_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occupant',
        ),
    ]
